version: "3.9"

services:
  vulnado:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vulnado-app
    ports:
      - "8080:8080"
    environment:
      PGPASSWORD: vulnado
      PGDATABASE: vulnado
      PGHOST: db
      PGUSER: postgres
      # Optional JVM opts for CI
      JAVA_OPTS: "-Xms256m -Xmx512m"
    depends_on:
      - db
      - internal_site
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12

  client:
    build:
      context: ./client
    container_name: vulnado-client
    ports:
      - "1337:80"

  db:
    image: postgres:13
    container_name: vulnado-db
    environment:
      POSTGRES_PASSWORD: vulnado
      POSTGRES_DB: vulnado
    ports:
      - "5432:5432"

  internal_site:
    build:
      context: ./internal_site
    container_name: vulnado-internal
