name: CI - Build, SAST/SCA, DAST

on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
  workflow_dispatch:

env:
  MAVEN_OPTS: "-Xmx2g"

jobs:
  build:
    name: Build & Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven repo
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build (skip tests)
        run: mvn -B -DskipTests package

      - name: Unit tests + coverage
        run: mvn -B test

      - name: Generate coverage report (JaCoCo)
        run: mvn -B jacoco:report

  sca_sast:
    name: SCA (OWASP DC) + SAST (SpotBugs & Sonar)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven repo
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # ----- SCA: Dependency-Check (blocking on CVSS>=7)
      - name: Cache Dependency-Check data
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository/org/owasp/dependency-check-data
            target/dependency-check-data
          key: ${{ runner.os }}-dc-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-dc-

      # Prefetch/upsert the CVE DB (reduces API calls during 'check')
      - name: Dependency-Check updateonly (prefetch DB)
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          mvn -B org.owasp:dependency-check-maven:updateonly \
            -Dnvd.api.key="${NVD_API_KEY}" \
            -DnvdApiKey="${NVD_API_KEY}"

      - name: OWASP Dependency-Check (SCA)
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          mvn -B org.owasp:dependency-check-maven:check \
            -Dformat=ALL \
            -DfailBuildOnCVSS=7 \
            -Dnvd.api.key="${NVD_API_KEY}" \
            -DnvdApiKey="${NVD_API_KEY}"


      # ----- SAST: SpotBugs (blocking on errors)
      - name: SpotBugs (SAST)
        run: mvn -B com.github.spotbugs:spotbugs-maven-plugin:4.9.8.1:check

      - name: Upload SpotBugs report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-report
          path: |
            **/spotbugsXml.xml
            **/spotbugsHtml.html

      # ----- SAST: SonarQube/SonarCloud (quality gate visible on PR)
      - name: SonarScanner
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B -DskipTests package
          mvn -B test jacoco:report
          mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
             -Dsonar.host.url="${SONAR_HOST_URL}" \
             -Dsonar.login="${SONAR_TOKEN}"

  dast_zap:
    name: DAST - OWASP ZAP baseline on ephemeral app
    runs-on: ubuntu-latest
    needs: sca_sast
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      - name: Build & start app
        run: docker compose up -d

      - name: Wait for app
        run: |
          for i in {1..40}; do
            if curl -fsS http://localhost:8080/ >/dev/null; then
              echo "App is ready"; exit 0
            fi
            sleep 5
          done
          echo "App did not start in time"; exit 1

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.17.0
        with:
          target: 'http://localhost:8080'
          rules_file_name: '.zap/rules.tsv'
          artifacts_name: 'zap-report'
          cmd_options: >
            -t http://localhost:8080
            -r zap_report.html
            -J zap_report.json
            -x zap_report.xml
            -m 5 -T 60

      # Fail CI if High/Critical alerts are present
      - name: Fail on High/Critical ZAP alerts
        run: |
          set -e
          test -f zap_report.json || { echo "No ZAP report"; exit 1; }
          HIGH=$(grep -o '"risk": *"High"' zap_report.json | wc -l | tr -d ' ')
          CRIT=$(grep -o '"risk": *"Critical"' zap_report.json | wc -l | tr -d ' ')
          echo "ZAP High=$HIGH, Critical=$CRIT"
          if [ "$HIGH" -gt 0 ] || [ "$CRIT" -gt 0 ]; then
            echo "Failing due to High/Critical ZAP findings"; exit 1
          fi

      - name: Upload ZAP artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            zap_report.html
            zap_report.json
            zap_report.xml

      - name: Teardown
        if: always()
        run: docker compose down -v
